### ISSUE TITLE
Information Visualization can be chosen multiple times

### ISSUE THREAD

**Issue by annalaczko** [Emile-Jn/curriculum-planner#3]
I added the VO InfoVis to my first semester. After that I could add it to other semesters too, without deleting it from the first semester

Btw, I love your app! 

Respect  ;)

**Comment by Emile-Jn** [comment]
Thank you very much:) and thanks for reporting the bug, InfoVis has different course codes depending on the semester, which is an exception, and I thought it would be complicated to tend to that. But it turns out that simply changing the course identification for requirements from `course.code` to `course.title && course.type` seems to fix it.
